### ISSUE TITLE
Documentation migration to GitHub

### ISSUE THREAD

**Issue by dpasukhi** [Open-Cascade-SAS/OCCT#100]
The main idea is simplify access for documentation for community.
The dox folder will have a copy in Wiki. The maintaining logic about 2 overview is not defined. Probably both will be supported or another way will be chosen. 

- [x] Create a action to build refman documentation
- [x] Migrate Overview documentation to pure markdawn and HTML syntax
- [x] Create a Wiki for OCCT
- [ ] Create a GitHub self-hosted refman documentation

**Comment by dpasukhi** [comment]
Wiki is created:https://github.com/Open-Cascade-SAS/OCCT/wiki
I was copied from my own https://github.com/dpasukhi/OCCT/wiki

**Comment by dpasukhi** [comment]
Self hosted will be not used.
https://dev.opencascade.org/doc/refman/html/
will be updated periodically.

**Comment by dpasukhi** [comment]
Merged weekly building refman and Wiki is open

**Comment by benj5378** [comment]
@dpasukhi, I want to express great gratitude for your efforts migrating to GitHub. It will make it much easier to contribute with PRs and give comments on issues, now that the code is on a widely known platform. Thank you very much for your great efforts migrating here.
